/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <string.h>
#include <stdio.h>


void
calc_prog_1(char *host,int a, int b, int selec)
{
	CLIENT *clnt;
	int  *result_1;
	dupla_int  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	calc_1_arg.a = a;
	calc_1_arg.b = b;
	switch (selec)
	{
	case 1: 
		result_1 = suma_1(&calc_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("result = %d\n", *result_1);
		}
		break;
	case 2: 
		result_1 = resta_1(&calc_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("result = %d\n", *result_1);
		}
		break;
	
	case 3: 
		result_1 = multiplicacion_1(&calc_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else{
			printf("result = %d\n", *result_1);
		}
		break;
	
	case 4: 
		result_1 = division_1(&calc_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("result = %d\n", *result_1);
		}
		break;
	
	default:
		break;
	}
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])//nombre_host_operacion_inta_intb 
{
	char *host,*operacion;
	int a, b, selec;

	

	if (argc != 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	operacion = argv[2];

	if ((a = atoi(argv[3])) == 0 && *argv[3] != '0') {
		fprintf(stderr, "invalid value: %s\n", argv[2]);
		exit(1);
	}
	if ((b = atoi(argv[4])) == 0 && *argv[4] != '0') {
		fprintf(stderr, "invalid value: %s\n", argv[3]);
		exit(1);
	}

	if(strcmp(operacion,"suma") == 0){
		selec = 1;
	}else if(strcmp(operacion,"resta") == 0){
		selec = 2;
	}else if(strcmp(operacion,"multiplicacion") == 0){
		selec = 3;
	}else if(strcmp(operacion,"division") == 0){
		selec = 4;
	}else{
		printf("No entraste a ningun caso");
	}
	calc_prog_1 (host,a,b,selec);
exit (0);
}
